--- 
title: "A solution to ggplot2-book"
author: "Raju Rimal"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
monofont: "Source Code Pro"
monofontoptions: "Scale=0.7"
github-repo: mathatistics/ggplot2-book
description: "This is a solution to the problems in ggplot2-book by Hadley Wickham"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(comment = NULL)
```


# Prerequisites {-}

This is a solution to the problems in ggplot2-book. In order to run all the solution, following packages need to be installed and loaded.


```{r, warning=FALSE, message = FALSE}
# devtools::install_github("hadley/tidyverse")
pkgs <- c("ggplot2", "dplyr", "pander")
for (pkg in pkgs) require(pkg, character.only = TRUE)
```

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
